-- http://luacheck.readthedocs.io/en/stable/warnings.html

std = "lua51"
max_line_length = false
codes = true
exclude_files = {
	".luacheckrc",
	".release",
	"**/Libs",
	"Babelfish.lua",
	"Localization/_export.lua",
}
ignore = {
	"11./SLASH_.*", -- Setting an undefined (Slash handler) global variable
	"11./BINDING_.*", -- Setting an undefined (Keybinding header) global variable
	"113/LE_.*", -- Accessing an undefined (Lua ENUM type) global variable
	"113/NUM_LE_.*", -- Accessing an undefined (Lua ENUM type) global variable
	"211", -- Unused local variable
	"211/L", -- Unused local variable "L"
	"211/CL", -- Unused local variable "CL"
	"212", -- Unused argument
	"213", -- Unused loop variable
	"311", -- Value assigned to a local variable is unused
	"314", -- Value of a field in a table literal is unused
	"42.", -- Shadowing a local variable, an argument, a loop variable.
	"43.", -- Shadowing an upvalue, an upvalue argument, an upvalue loop variable.
	"542", -- An empty if branch
}
files["Modules/Phase**"].globals = {
	"UnitInPhase", -- classic compat
}
files["Modules/Runes_Classic/*"].globals = {
	"GetRuneType", -- classic compat
}
files["Modules/HappinessIcon_Classic/*"].globals = {
	"GetPetHappiness", -- classic compat
}
globals = {
	-- Third-party
	"LibStub",
	"PitBull4",
	"oRA3",

	-- FrameXML
	"AzeriteUtil",
	"BasicMessageDialog",
	"Clamp",
	"ChatFontNormal",
	"CombatFeedbackText",
	"CopyTable",
	"CopyTableSafe",
	"CopyValuesAsKeys",
	"CountTable",
	"DEFAULT_CHAT_FRAME",
	"GameTooltip",
	"GameTooltip_SetDefaultAnchor",
	"GetKeysArray",
	"GetKeysArraySortedByValue",
	"GetPairsArray",
	"GetRandomArrayEntry",
	"GetRandomTableValue",
	"GetValuesArray",
	"MergeTable",
	"Mixin",
	"Saturate",
	"SpellIsSelfBuff",
	"StaticPopup_Show",
	"StaticPopupDialogs",
	"StatusTrackingBarManager",
	"SOUNDKIT",
	"TooltipUtil",
	"UIErrorsFrame",
	"UIParent",
	"tAppendAll",
	"tCompare",
	"tContains",
	"tDeleteItem",
	"tFilter",
	"tIndexOf",
	"tInsertUnique",
	"tInvert",
	"tInvertToArray",
	"tUnorderedRemove",
	"ipairs_reverse",

	"Enum",
	"CurveConstants",

	-- Classic
	"WOW_PROJECT_ID",
	"WOW_PROJECT_MAINLINE",

	-- Functions
	"AbbreviateNumbers",
	"BreakUpLargeNumbers",
	"C_AddOns",
	"C_AzeriteItem",
	"C_ChatInfo",
	"C_CreatureInfo",
	"C_CurveUtil",
	"C_DurationUtil",
	"C_GossipInfo",
	"C_IncomingSummon",
	"C_Item",
	"C_LFGInfo",
	"C_MajorFactions",
	"C_PartyInfo",
	"C_PvP",
	"C_Reputation",
	"C_Secrets",
	"C_SpecializationInfo",
	"C_Spell",
	"C_SpellBook",
	"C_StringUtil",
	"C_Timer",
	"C_TooltipInfo",
	"C_UnitAuras",
	"CancelItemTempEnchantment",
	"CancelUnitBuff",
	"CheckInteractDistance",
	"ClassicExpansionAtLeast",
	"ClassicExpansionAtMost",
	"CreateAbbreviateConfig",
	"CreateColor",
	"CreateFrame",
	"DestroyTotem",
	"GetBattlefieldStatus",
	"GetCVarBool",
	"GetClassicExpansionLevel",
	"GetComboPoints",
	"GetBuildInfo",
	"GetFriendshipReputation",
	"GetInventoryItemLink",
	"GetInventoryItemQuality",
	"GetLocale",
	"GetManagedEnvironment",
	"GetMaxPlayerLevel",
	"GetMouseFocus",
	"GetNumClasses",
	"GetNumGroupMembers",
	"GetPowerRegenForPowerType",
	"GetPVPTimer",
	"GetPartyAssignment",
	"GetPetExperience",
	"GetQuestDifficultyColor",
	"GetRaidRosterInfo",
	"GetRaidTargetIndex",
	"GetReadyCheckStatus",
	"GetRuneCooldown",
	"GetScreenHeight",
	"GetScreenWidth",
	"GetShapeshiftFormID",
	"GetTalentInfoBySpecialization",
	"GetThreatStatusColor",
	"GetTime",
	"GetUnitEmpowerHoldAtMaxTime",
	"GetUnitPowerBarInfo",
	"GetWatchedFactionInfo",
	"GetWeaponEnchantInfo",
	"GetXPExhaustion",
	"InCombatLockdown",
	"IsInInstance",
	"IsInGroup",
	"IsInRaid",
	"IsPlayerInWorld",
	"IsPlayerSpell",
	"IsPVPTimerRunning",
	"IsResting",
	"IsShiftKeyDown",
	"IsSpellKnown",
	"PartyUtil",
	"PlaySound",
	"PlaySoundFile",
	"RegisterAttributeDriver",
	"RegisterUnitWatch",
	"SecureHandlerExecute",
	"SecureHandlerSetFrameRef",
	"SetPortraitTexture",
	"ShowBossFrameWhenUninteractable",
	"SpellGetVisibilityInfo",
	"UnitAffectingCombat",
	"UnitBattlePetLevel",
	"UnitBattlePetType",
	"UnitCanAttack",
	"UnitCastingInfo",
	"UnitCastingDuration",
	"UnitChannelInfo",
	"UnitChannelDuration",
	"UnitClass",
	"UnitClassBase",
	"UnitClassFromGUID",
	"UnitClassification",
	"UnitCreatureFamily",
	"UnitCreatureType",
	"UnitDetailedThreatSituation",
	"UnitEmpoweredChannelDuration",
	"UnitExists",
	"UnitFactionGroup",
	"UnitGUID",
	"UnitGetIncomingHeals",
	"UnitGetTotalAbsorbs",
	"UnitGroupRolesAssigned",
	"UnitHasIncomingResurrection",
	"UnitHasVehiclePlayerFrameUI",
	"UnitHasVehicleUI",
	"UnitHealth",
	"UnitHealthMax",
	"UnitHealthMissing",
	"UnitHealthPercent",
	"UnitHonorLevel",
	"UnitInAnyGroup",
	"UnitInParty",
	"UnitInPartyIsAI",
	"UnitInRaid",
	"UnitInRange",
	"UnitIsAFK",
	"UnitIsBattlePetCompanion",
	"UnitIsConnected",
	"UnitIsDND",
	"UnitIsDead",
	"UnitIsDeadOrGhost",
	"UnitIsEnemy",
	"UnitIsFeignDeath",
	"UnitIsFriend",
	"UnitIsGhost",
	"UnitIsGroupLeader",
	"UnitIsMercenary",
	"UnitIsOtherPlayersPet",
	"UnitIsPVP",
	"UnitIsPVPFreeForAll",
	"UnitIsPlayer",
	"UnitIsQuestBoss",
	"UnitIsTapDenied",
	"UnitIsUnit",
	"UnitIsVisible",
	"UnitIsWildBattlePet",
	"UnitLevel",
	"UnitName",
	"UnitNameFromGUID",
	"UnitPartialPower",
	"UnitPlayerControlled",
	"UnitPlayerOrPetInRaid",
	"UnitPower",
	"UnitPowerDisplayMod",
	"UnitPowerMax",
	"UnitPowerMissing",
	"UnitPowerPercent",
	"UnitPowerType",
	"UnitPhaseReason",
	"UnitRace",
	"UnitReaction",
	"UnitSelectionColor",
	"UnitThreatSituation",
	"UnitXP",
	"UnitXPMax",
	"UnregisterAttributeDriver",
	"UnregisterUnitWatch",
	"abs",
	"bit",
	"ceil",
	"date",
	"debugstack",
	"floor",
	"format",
	"geterrorhandler",
	"hooksecurefunc",
	"math",
	"max",
	"min",
	"string",
	"strjoin",
	"strsplit",
	"strtrim",
	"table",
	"tostringall",
	"wipe",

	"issecretvalue",
	"issecrettable",
	"hasanysecretvalues",


	-- Strings
	"ALTERNATE_POWER_INDEX",
	"CANCEL",
	"CAT_FORM",
	"CLASS",
	"CLASS_SORT_ORDER",
	"DAMAGER",
	"DAY_ONELETTER_ABBR",
	"DAYS_ABBR",
	"DECIMAL_SEPERATOR",
	"FIRST_NUMBER_CAP_NO_SPACE",
	"FULL_PLAYER_NAME",
	"HEALER",
	"HOUR_ONELETTER_ABBR",
	"HOURS_ABBR",
	"LARGE_NUMBER_SEPERATOR",
	"LFG_FOLLOWER_NAME_PREFIX",
	"LOCALIZED_CLASS_NAMES_MALE",
	"MAX_PARTY_MEMBERS",
	"MAX_RAID_MEMBERS",
	"MINUTE_ONELETTER_ABBR",
	"MINUTES_ABBR",
	"NONE",
	"NUM_BAG_SLOTS",
	"PET_TYPE_SUFFIX",
	"RAID_CLASS_COLORS",
	"RAID_TARGET_1",
	"RAID_TARGET_2",
	"RAID_TARGET_3",
	"RAID_TARGET_4",
	"RAID_TARGET_5",
	"RAID_TARGET_6",
	"RAID_TARGET_7",
	"RAID_TARGET_8",
	"RELOADUI",
	"SECOND_NUMBER_CAP_NO_SPACE",
	"SECOND_ONELETTER_ABBR",
	"SECONDS_ABBR",
	"TANK",
	"TOOLTIP_BATTLE_PET",
	"UNKNOWN",
}
